[project]
authors = ["Katy Scott <k.l.scott16@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "analyze_readii_outputs"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
process = {cmd = "python -m readii_analysis.run_data_setup_for_prediction_models --dataset_name RADCURE --extraction_method radiomic --raw_feature_dir readii_outputs", cwd = "./workflow/scripts/python"}

[dependencies]
python = ">=3.12.6,<4"
pandas = ">=2.2.3,<3"
ipykernel = ">=6.29.5,<7"
pyyaml = ">=6.0.2,<7"
matplotlib = ">=3.9.2,<4"
seaborn = ">=0.13.2,<0.14"
checkmate = ">=0.9.3,<0.10"
yaml = ">=0.2.5,<0.3"
scipy = ">=1.14.1,<2"
