# Config file for Head-Neck-Radiomics-HN1
dataset_name: Head-Neck-Radiomics-HN1

### CLINICAL VARIABLE INFORMATION ###
# Event values should be in the order [Alive_value, Dead_value]
outcome_variables:
    time_label: "overall_survival_in_days"
    event_label: "event_overall_survival"
    convert_to_years: True

exclusion_variables: {}

train_test_split: 
    split: False
    split_variables: {}
    impute: 
