# Config file for RADCURE
dataset_name: RADCURE 

### CLINICAL VARIABLE INFORMATION ###
# Event values should be in the order [Alive_value, Dead_value]
outcome_variables:
    time_label: "Length FU"
    event_label: "Status"
    convert_to_years: False

exclusion_variables: {'Ds Site': ['Sarcoma', 'Unknown', 'Paraganglioma', 'Salivary Glands', 'Other', 'benign tumor', 'Orbit', 'Lacrimal gland', 'Skin']}

train_test_split:
    split: True
    split_variable: {'RADCURE-challenge': ['training', 'test']}
    impute: 'training'


image_types: ["original", "shuffled_full","shuffled_roi","shuffled_non_roi","randomized_sampled_full","randomized_sampled_roi","randomized_sampled_non_roi"] #["shuffled_full","shuffled_roi","shuffled_non_roi","randomized_full","randomized_roi","randomized_non_roi","randomized_sampled_full","randomized_sampled_roi", "randomized_sampled_non_roi"]
